package com.mariustanke.domotask.ui.theme
import androidx.compose.ui.graphics.Color

// Light scheme — brand: primary #1565C0, secondary #66BB6A
// Surfaces tinted with blue to avoid flat white
val primaryLight = Color(0xFF1565C0)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD1E4FF)
val onPrimaryContainerLight = Color(0xFF0D47A1)
val secondaryLight = Color(0xFF4CAF50)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB9F6CA)
val onSecondaryContainerLight = Color(0xFF1B5E20)
val tertiaryLight = Color(0xFFFF8F00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFE0B2)
val onTertiaryContainerLight = Color(0xFFE65100)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4F7FB)       // blue-tinted off-white
val onBackgroundLight = Color(0xFF1A1C20)
val surfaceLight = Color(0xFFF8FAFD)           // very subtle blue tint
val onSurfaceLight = Color(0xFF1A1C20)
val surfaceVariantLight = Color(0xFFE3EBF2)    // blue-gray tint
val onSurfaceVariantLight = Color(0xFF42474E)
val outlineLight = Color(0xFF72787E)
val outlineVariantLight = Color(0xFFC2C8CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFA8C8FF)
val surfaceDimLight = Color(0xFFD9DDE3)
val surfaceBrightLight = Color(0xFFF8FAFD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F3F8)  // subtle blue tint
val surfaceContainerLight = Color(0xFFEAEEF4)     // blue-tinted
val surfaceContainerHighLight = Color(0xFFE4E8EF)  // blue-tinted
val surfaceContainerHighestLight = Color(0xFFDFE3EA)

// Dark scheme — brand colors lightened for readability on dark bg
val primaryDark = Color(0xFF64B5F6)
val onPrimaryDark = Color(0xFF0D47A1)
val primaryContainerDark = Color(0xFF1565C0)
val onPrimaryContainerDark = Color(0xFFD1E4FF)
val secondaryDark = Color(0xFF81C784)
val onSecondaryDark = Color(0xFF0A3D0C)
val secondaryContainerDark = Color(0xFF2E7D32)
val onSecondaryContainerDark = Color(0xFFB9F6CA)
val tertiaryDark = Color(0xFFFFB74D)
val onTertiaryDark = Color(0xFF3E2723)
val tertiaryContainerDark = Color(0xFFE65100)
val onTertiaryContainerDark = Color(0xFFFFE0B2)
val errorDark = Color(0xFFF85149)
val onErrorDark = Color(0xFF141821)
val errorContainerDark = Color(0xFF8E1519)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141821)
val onBackgroundDark = Color(0xFFE6EDF3)
val surfaceDark = Color(0xFF141821)
val onSurfaceDark = Color(0xFFE6EDF3)
val surfaceVariantDark = Color(0xFF252A33)
val onSurfaceVariantDark = Color(0xFF9BA4AE)
val outlineDark = Color(0xFF353C47)
val outlineVariantDark = Color(0xFF252A33)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6EDF3)
val inverseOnSurfaceDark = Color(0xFF141821)
val inversePrimaryDark = Color(0xFF1565C0)
val surfaceDimDark = Color(0xFF141821)
val surfaceBrightDark = Color(0xFF323842)
val surfaceContainerLowestDark = Color(0xFF0B0F16)
val surfaceContainerLowDark = Color(0xFF1A1F28)
val surfaceContainerDark = Color(0xFF20252E)
val surfaceContainerHighDark = Color(0xFF252A33)
val surfaceContainerHighestDark = Color(0xFF323842)

// Urgency background colors — dark theme
val UrgencyGreenDark = Color(0xFF1A2F23)
val UrgencyBlueDark = Color(0xFF1A2535)
val UrgencyAmberDark = Color(0xFF2A2518)
val UrgencyOrangeDark = Color(0xFF2F2118)
val UrgencyRedDark = Color(0xFF2F1A1A)

// Urgency background colors — light theme
val UrgencyGreenLight = Color(0xFFE8F5E9)
val UrgencyBlueLight = Color(0xFFE3F2FD)
val UrgencyAmberLight = Color(0xFFFFF8E1)
val UrgencyOrangeLight = Color(0xFFFFF3E0)
val UrgencyRedLight = Color(0xFFFFEBEE)

// Urgency text accent colors (shared, work on both themes)
val UrgencyGreenText = Color(0xFF2E7D32)
val UrgencyBlueText = Color(0xFF1565C0)
val UrgencyAmberText = Color(0xFFF9A825)
val UrgencyOrangeText = Color(0xFFEF6C00)
val UrgencyRedText = Color(0xFFC62828)
